/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphique;

import java.util.Timer;
import java.util.TimerTask;
import wild_fire_simu.Terrain;

/**
 *
 * @author ASUS
 */
public class Fenetre extends javax.swing.JFrame {

    private grillePanel grPanel;
    private Timer t;
    public Fenetre() {
        initComponents();
        grPanel=new grillePanel();
        this.add(grPanel); // on ajoute à notre fenêtre notre panel
        this.pack(); // permet de bien ajuster notre panel dans notre fenêtre
    }
    
    public class Tache extends TimerTask {
    public void run(){ 
        grPanel.getGr1().changeColor(); 
        grPanel.repaint();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Demarrer = new javax.swing.JButton();
        GeneTerrain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Demarrer.setText("Demarrer");
        Demarrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemarrerActionPerformed(evt);
            }
        });

        GeneTerrain.setText("Générer terrain");
        GeneTerrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneTerrainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Demarrer)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 295, Short.MAX_VALUE)
                .addComponent(GeneTerrain))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Demarrer)
                .addGap(18, 18, 18)
                .addComponent(GeneTerrain)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DemarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemarrerActionPerformed
        terrain.Depart_Feu(1); // on lance nos départs de feu
        t=new Timer(); 
        t.schedule(new Tache(),0,2000); // on execute notre tache toutes les 2000ms
    }//GEN-LAST:event_DemarrerActionPerformed

    private void GeneTerrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneTerrainActionPerformed
        
        terrain.Affec_Vege(50, 10, 1); // on place la végétation avec une disposition unique
        grPanel.repaint(); // on repaint notre panel pour mettre à jour les couleurs du nouveau panel
        
    }//GEN-LAST:event_GeneTerrainActionPerformed

    /**
     * @param args the command line arguments
     */
    
    static Terrain terrain =new Terrain();
    
    
    public static void main(String args[]) {
        
        Fenetre window=new Fenetre();
        window.setVisible(true);
        //new Fenetre().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Demarrer;
    private javax.swing.JButton GeneTerrain;
    // End of variables declaration//GEN-END:variables
}
