/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Graphics;

import java.util.Timer;
import java.util.TimerTask;
import wild_fire_simu.Terrain;
import wild_fire_simu.Vent;

/**
 *
 * @author ASUS
 */
public class Fenetre extends javax.swing.JFrame {

    private grillePanel grPanel;
    private Timer t;
    public Fenetre() {
        initComponents();
    }
    
    public class Tache extends TimerTask {
        public void run(){
            grPanel.getGr1().changeColor(terrain,wind); 
            grPanel.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Demarrer = new javax.swing.JButton();
        GeneTerrain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Demarrer.setText("Demarrer");
        Demarrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemarrerActionPerformed(evt);
            }
        });

        GeneTerrain.setText("Générer terrain");
        GeneTerrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneTerrainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Demarrer)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 475, Short.MAX_VALUE)
                .addComponent(GeneTerrain))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Demarrer)
                .addGap(18, 18, 18)
                .addComponent(GeneTerrain)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // bouton pour lancer une simulation
    private void DemarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemarrerActionPerformed
        if(DemarrageOK == true){
            terrain.Depart_Feu(1); // on lance nos départs de feu
            System.out.println("activé");
            t = new Timer(); 
            t.schedule(new Tache(),0,100); // on execute notre tache toutes les 100ms
            DemarrageOK=false;
        }
    }//GEN-LAST:event_DemarrerActionPerformed

    // bouton de la génération du terrain
    private void GeneTerrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneTerrainActionPerformed
        terrain.CreaTableau(90, 800, 800); // on créer un terrain
        terrain.Affec_Vege(75, 50, 11092001); // on place la végétation avec une disposition unique
        wind=new Vent("NORD", 3); // on initialise notre Vent
        grPanel = new grillePanel(terrain);
        this.add(grPanel); // on ajoute à notre fenêtre notre panel
        this.pack();
        grPanel.repaint(); // on repaint notre panel pour mettre à jour les couleurs du nouveau panel
        DemarrageOK = true; // notre boolean devient vrai ce qui permet de lancer une simulation
    }//GEN-LAST:event_GeneTerrainActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // attributs : 
    static Terrain terrain =new Terrain();  
    static Vent wind;
    boolean DemarrageOK = false;
    
    public static void main(String args[]) {
        
        Fenetre window=new Fenetre();
        window.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Demarrer;
    private javax.swing.JButton GeneTerrain;
    // End of variables declaration//GEN-END:variables
}
